### PR TITLE
Fix too many redirects bug

### LINKED ISSUE #1704: Too many redirects error on group assignment
**Describe the bug**

When teachers attempt to accept [the team assignment](https://classroom.github.com/group-assignment-invitations/d6781417e41ebad9dfde584fbba07f6b) for Campus Advisors they get an error showing too many redirects.

**To Reproduce**
1. Go to '...'https://education.github.com/teachers/advisors
2. Click on '....'Module 3 Group work
3. Scroll down to '....'Wait to accept assignment

**Expected behavior**

Accept a group assignment and choose a team.

**Screenshots**

screenshot 2018-11-20 08 39 16

**Additional context**

cc @ccannon94

### PR DESCRIPTION
**Pull request by BenEmdon**
## What
This PR proposes the following changes:
* removed the before_action `check_group_not_previous_acceptee` from `group_assignment_invitations_controller.rb`. This before_action was previously solving an edge case before the `group_import_resiliency` changes went into place, but is no longer needed since we now have `route_based_on_status`.
* in `#create_repo` we now check if a pre existing assignment repo is present. If that assignment repo is ready, succeed otherwise retry the repo creation process.

## Note
A lot of dead code still exists behind the `group_import_resiliency` and we must make an issue to clean that up!

Fixes #1704

### CODE REVIEW

File: spec/controllers/group_assignment_invitations_controller_spec.rb [hunk 1]
```diff
@@ -326,32 +326,10 @@
 
         it "allows user to join" do
           patch :accept_invitation, params: { id: invitation.key, group: { id: group.id } }
-          expect(group_assignment.group_assignment_repos.count).to eql(1)
           expect(student.repo_accesses.count).to eql(1)
         end
       end
 
-      context "github repository with the same name already exists" do
```
Comment (BenEmdon) [inline spec/controllers/group_assignment_invitations_controller_spec.rb]: These tests can be removed because `#accept_invitation` no longer creates a GitHub repository after the `group_import_resiliency` changes.

File: spec/models/group_assignment_invitation_spec.rb [hunk 2]
```diff
@@ -58,19 +58,7 @@
...
 
-    after(:each) do
-      RepoAccess.destroy_all
-      Group.destroy_all
-      GroupAssignmentRepo.destroy_all
-      GroupInviteStatus.destroy_all
-    end
-
     context "success result" do
-      it "success?" do
```
Comment (BenEmdon) [inline spec/models/group_assignment_invitation_spec.rb]: This test can be removed since `#redeem_for` no longer returns `success` when a assignment repo doesn't yet exist. Instead, after the `group_import_resiliency` it returns `pending`.
