### PR TITLE
Finally the fix the terrible token bug

### LINKED ISSUE #445: Don't reduce OAuth scopes
When visiting a page that requires fewer scopes, we currently ask the user to reduce permissions. This can lead to problems for organization owners, so let's stop reducing scopes.

What's happening is that if any organization administrator accepts an assignment we downgrade the authentication token for that user. Since we create the repositories as the organization administrator, a downgraded token will lead to permissions errors. As a workaround, all admins should log out of Classroom and log in again. Do not accept an assignment using an organization administrator account.

### PR DESCRIPTION
**Pull request by tarebyte**
This closes #445 where a user can reduce their token scopes if they sign in as teacher, and then sign in as a student.

Closes #604 #461 #46 #464 #497 #557 #560 #567 #581 #586 #588 #597 #604 

/cc @johndbritton @mkcode 

Apologies for the cassettes diff

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -28,7 +28,7 @@ def current_scopes
   end
 
   def required_scopes
-    %w(user:email repo delete_repo admin:org)
+    Classroom::Scopes::TEACHER
```
Comment (johndbritton) [inline app/controllers/application_controller.rb]: I like this.

File: app/models/user.rb [hunk 2]
```diff
@@ -37,10 +39,38 @@ def github_client
...
+  def ensure_no_token_scope_loss
+    return true if token_was.blank?
+    return true unless token_changed?
+
+    old_scopes = GitHub::Token.scopes(token_was)
+    new_scopes = GitHub::Token.scopes(token)
+
+    # This is naive, if the token scopes ever change
+    # come back an revist this.
+    return true if old_scopes.size < new_scopes.size
```
Comment (johndbritton) [inline app/models/user.rb]: don't love this, but it would only matter if we change the scopes we request for the different roles

Comment (tarebyte) [inline app/models/user.rb]: @johndbritton we can do a smarter comparison here if you think that's better.

File: spec/lib/classroom/scopes_spec.rb [hunk 3]
```diff
@@ -0,0 +1,18 @@
+# frozen_string_literal: true
+require 'rails_helper'
+
+describe Classroom::Scopes do
```
Comment (johndbritton) [inline spec/lib/classroom/scopes_spec.rb]: Could we add a test in here that will fail if the ordering the different roles by `scopes.size` changes and invalidates the logic we're using to make sure we don't downgrade. That way that dependency is codified.

File: app/models/user.rb (hunk 2 above)
Comment (johndbritton) [inline app/models/user.rb]: Yeah, I think we should.

I think the logic should be as follows:

* If the new token has the same scopes, keep the new token.
* If the new token has different scopes, compare scopes
  * If scopes are only added, keep the new token
  * If scopes are only removed, keep the old token
  * If scopes are added and removed ???

The only odd case is if scopes are added and removed, not quite sure to do there. I think the only solution would be to store multiple tokens. In our case I think we should raise an error. It should never happen, but if we try and do it in the future we want to know that it's unimplemented.

Comment (tarebyte) [inline app/models/user.rb]: I think there's a good amount of logic that would go into this, since this works, and we aren't changing out scopes, I'm going to punt on this for now and come back to it.

File: spec/lib/classroom/scopes_spec.rb (hunk 3 above)
Comment (tarebyte) [inline spec/lib/classroom/scopes_spec.rb]: Done in 840fd59

Comment (johndbritton) [inline spec/lib/classroom/scopes_spec.rb]: Yeah, this is good enough to jog our memory if things need to be changed in the future.
