### PR TITLE
Prevent teachers from using empty repos as starter code repositories

### LINKED ISSUE #1906: Starter code importer hangs when importing from empty repository
**Describe the bug**
The starter code importer hangs/breaks when the starter code repo is empty.

**To Reproduce**
1. Create a new assignment
2. Select an empty repo to use as starter code
3. Accept invitation 
4. Starter code importer hangs

**Expected behavior**
We should warn teachers if the starter code repo is empty and prevent them from choosing it.

We can easily fix this by checking the `size` attribute on the `github_repository`. I've confirmed that empty repos have a size of 0.

### PR DESCRIPTION
**Pull request by EricPickup**
## What
#1931 aimed to fix this but we ran into edge cases when using the number of commits to determine if a repo was empty. We also tried using the `size` attribute which was unreliable, described in #1970.

Fixes #1906, which causes the importer to hang when importing from an empty repo.

This PR adds a validator to Assignment and GroupAssignment that checks if their starter code repo is empty. It will prevent teachers from saving/creating an assignment with an empty repo selected.

## How
This time we'll be checking the repository's [`Contents`](https://www.rubydoc.info/github/pengwynn/octokit/Octokit/Client/Contents#contents-instance_method), which lists the actual file contents of the repo. When the repository contains no content, the GitHub api returns an error stating that the repo is empty.

ex:
Empty repo
https://api.github.com/repos/classroomtestorg/daasdsadsadasdasd-ericpickup-test3/contents

Populated repo
https://api.github.com/repos/education/classroom/contents

### CODE REVIEW

File: app/models/github_repository.rb [hunk 1]
```diff
@@ -161,7 +161,9 @@ def number_of_commits
   end
 
   def empty?
```
Comment (EricPickup) [inline app/models/github_repository.rb]: Reviewers - this method is the only thing changed from the original PR

Comment (srinjoym) [reply app/models/github_repository.rb]: Could we use the `GitHub::Errors` class here to follow the pattern in the other methods in the file? Not sure if there's anything different about this check but it could possibly look like this:

```
  def empty?
    GitHub::Errors.with_error_handling do
      @client.contents(full_name).empty?
    end
  rescue GitHub::Error
    return true
  end
```

Comment (d12) [reply app/models/github_repository.rb]: :+1:

Comment (EricPickup) [reply app/models/github_repository.rb]: @srinjoym great suggestion!
