### PR TITLE
Fix bug when there is an error on classroom settings

### LINKED ISSUE #2086: Styling breaks when there's an error on classroom settings form
**Describe the bug**
We have some style issues when an error comes up on the manage classroom page.

**To Reproduce**
1. Go to "Manage classroom"
2. Make the classroom title blank
3. Save

**Screenshots**
**Before:**
image

**After:**
image

Notice the manage classroom button is off, and the banner is quite different in size and content.

### PR DESCRIPTION
**Pull request by GQuirino**
fix #2086 
Bug: In the banner, the title of the organization is being erased if receive some validation error, because of that missing information the height of that banner was lower than the usual.

fix: before render the edit page, reload the current organization to get the last information saved

### CODE REVIEW

**Comment by GQuirino** [comment]
That field title, in classroom settings, is getting the organization title as default, should i set the default value as empty?

**Comment by stephaniegiang** [comment]
@GQuirino For that page, we should grab the original classroom name and org name.

**Comment by stephaniegiang** [comment]
Oh also, ping us when this is ready for review 😄

**Comment by d12** [comment]
Thanks for the contribution! One thing I'd like to add, are you able to write a regression test for this?

**Comment by GQuirino** [comment]
@d12 sure !!

**Comment by GQuirino** [comment]
@12 test done!

**Comment by stephaniegiang** [comment]
You have some syntax issues so CI is failing.

But you can run `rubocop -a spec/controllers/organizations_controller_spec.rb` and that command will automatically fix it for you. Then commit those changes. I don't have push permissions.

**Comment by GQuirino** [comment]
@stephaniegiang syntax fixed :smile: :+1:

File: spec/controllers/organizations_controller_spec.rb [hunk 1]
```diff
@@ -285,11 +285,22 @@
...
+        expect(response).to redirect_to(organization_path(Organization.find(organization.id)))
+      end
+    end
+
+    context "when fail" do
+      it "not change current organization title" do
+        options = { title: " " }
+        patch :update, params: { id: organization.slug, organization: options }
+
+        expect(assigns(:current_organization).title).not_to eql(options[:title])
```
Comment (d12) [inline spec/controllers/organizations_controller_spec.rb]: Can you add one final assertion in here showing we redirect to :edit? Then I think this will be good to go :sparkles:

Comment (GQuirino) [reply spec/controllers/organizations_controller_spec.rb]: all done

**Comment by d12** [comment]
It looks like your tests are failing on some cassette errors. Let us know if you need help resolving those.

**Comment by GQuirino** [comment]
i updated the cassettes, ready to review
