### PR TITLE
fix NoMethodError for NullGitHubUser

### LINKED ISSUE #329: paginating to page2 does not work We're sorry, but something went wrong.
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Airbrake Error 1534922897515050480

Some student did delete their account, maybe it broke something?

### PR DESCRIPTION
**Pull request by tarebyte**
Fixes #329 

/cc @johndbritton 

we definitely need tests for these at some point.

### CODE REVIEW

File: app/models/null_git_hub_user.rb [hunk 1]
```diff
@@ -6,4 +6,8 @@ def html_url
   def login
     'ghost'
   end
+
+  def name
+    'ghost'
```
Comment (johndbritton) [inline app/models/null_git_hub_user.rb]: I prefer to use "Deleted user" here as that's the name that is associated with https://github.com/ghost and makes more sense when the user sees that.

**Comment by tarebyte** [comment]
@johndbritton updated the PR based on your suggestion
